### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by johannesschobel** [BrunnerLivio/nestjs-monorepo-starter#1]
Dear @BrunnerLivio ,

first of all, i would like to thank you for this starter package and the time and effort you put into it.
I downloaded the repository and followed your instructions in order to get it to work. I was able to properly run the `GET /` route (and see the `Hello World` output). :+1: 

However, i have a few questions regarding this setup - maybe you can answer these questions?
1) I have a hard time understanding, in which case the modules are installed into `/node_modules` (root folder) and when into `/packages/X/node_modules`. For example, in your setup the `api` uses `core`. However, if i run `yarn && yarn bootstrap`, the requested `core` package is not located within `/packages/api/node_modules` but rather in `/node_modules`.

2) I am not able to follow the references in my IDE (Webstorm), if i click on the `import { CoreService } ... ;` in the `projects/api/src/app.controller.ts` file, i cannot open the respective file automatically. However, if i click on a respective method from the `CoreService` (e.g., `coreService.getHello()` it works. Maybe this is related to 1)?

3) In order to directly run specific tests from the IDE (not the console), i had to add a `jest` configuration in respective `package.json` file in each package

4) same applies for `e2e tests`.

I would like to "better" structure my application; e.g., i would like to have a `packages` folder, where i have code that may be used by different applications. And then i would like to have a `apps` folder, where i put respective application code. 
I was able to get quite far with configuring lerna to use `packages` and `apps` folder, also configuring `yarn workspaces`, but somewhere i got lost.. Have you tried something like this?

All the best!

**Comment by BrunnerLivio** [comment]
@johannesschobel Thank you for your questions.

1) I think what yarn does is basically bootstrapping all packages into the root `node_modules` folder like npm. In case the packagaes have the same dependency BUT a different version, it will bootstrap it into the node_modules folder of the package e.g. `packages/core/node_modules`.

2) VSCode developer here - can not really help you with this issue. Maybe try to upgrade your IDE or maybe look into TSConfig path aliases.

3+4) Will look into it

Hmm no I haven’t tried that. But is it really needed though?

**Comment by johannesschobel** [comment]
Dear @BrunnerLivio ,

thank you very much for your fast reply on this - very much appreciated! Regarding
1) Oh, ok - that seems reasonable :thinking: . However, when bundling all together, yarn (or lerna!?) uses dependencies from `root-node_modules` and `package-node_modules` in order to make an executable bundle, right?!

2) Can you recommend some good VSCode plugins? I also thought about riding the VSCode hype-train :laughing: 

3 & 4) I added this block:
```
"jest": {
    "moduleFileExtensions": ["js", "json", "ts"],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
```
to **each** `package.json` in the `packages/` folder, in order to make it "directly runnable via IDE" (e.g., "run commands")

I thought about splitting the `apps` into different directories in order to make the code more understandable. But i guess, this is just a personal favour..

All the best

**Comment by johannesschobel** [comment]
Oh.. and another thing..
If i directly import a class from another package, it is linked via
```
import { Whatever } from "@monoapp/whatever/src/models/whatever.entity";
```

Note that there is a `src` in this path - however, it should not occur, because of styleguide reasons..
Do you know, how to solve this?

All the best

**Comment by BrunnerLivio** [comment]
@johannesschobel 

1. Yarn does not bundle your application. What yarn workspaces does is just lay out different `node_modules` folder for each package, as described before. Thanks to the node module resolution it then will search in the closest node_modules folder (package-`node_modules`-folder). If the package is not found in there, it will search a level up (root-`node_modules`-folder). [Read more](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

2. I prefer a minimized IDE, but I definitely have some must haves:

- Prettier - Code Formatter
- Version Lens
- TypeLens
- angular2-inline
- eslint
- tslint

> If i directly import a class from another package, it is linked via [...]

Could be possible that VSCode does not interpret Yarn workspaces correctly yet. I usually import this manually :)
